pipeline
{
    agent
    {
        label 'docker-node'
    }
    environment
    {
        DOCKERHUB_CREDENTIALS=credentials('docker-hub')
    }
    stages
    {
        stage('Clone')
        {
            steps
            {
                git branch: 'main', url: 'http://192.168.111.101:3000/exam/exam'
            }  
        }
        stage('Create a network')
        {
            steps
            {
                sh '''
                docker network rm exam-net || true
                docker network ls | grep exam-net || docker network create exam-net
                '''
            }
        }
        stage('Build the Images')
        {
            steps
            {
                sh 'docker image rm -f exam-generator exam-storage exam-client || true'
                sh 'docker compose -f docker-compose-run.yml build'
            }
        }
        stage('Run the Containers')
        {
            steps
            {
                sh 'docker container rm -f con-generator con-storage con-client || true'
                sh 'docker compose -f docker-compose-run.yml up -d'
            }
        }
        stage('Test')
        {
            steps
            {
                script
                {
                    echo 'Test #1 - Reachability'
                    sh 'sleep 5s && echo $(curl --write-out "%{http_code}" --silent --output /dev/null http://localhost:8080) | grep 200'

                    echo 'Test #2 - Check if Fun Facts Appears'
                    sh "curl --silent http://localhost:8080 | grep 'Fun Facts'"  
                }
            }
        }
        stage('CleanUp')
        {
            steps
            {
                sh 'docker compose -f docker-compose-run.yml down'
            }
        }
        stage('Login')
        {
            steps
            {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }
        stage('Push')
        {
            steps
            {
                sh 'docker image rm ilkothetiger/exam-generator ilkothetiger/exam-storage ilkothetiger/exam-client || true'
                sh 'docker image tag exam-generator ilkothetiger/exam-generator'
                sh 'docker image tag exam-storage ilkothetiger/exam-storage'
                sh 'docker image tag exam-client ilkothetiger/exam-client'
                sh 'docker push ilkothetiger/exam-generator'
                sh 'docker push ilkothetiger/exam-storage'
                sh 'docker push ilkothetiger/exam-client'
            }
        }
        stage('Deploy')
        {
            steps
            {
                sh 'docker image rm -f exam-generator-1 exam-storage-1 exam-client-1 || true'
                sh 'docker compose -f docker-compose-deploy.yml up -d'
            }
        }
    }
}