global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'jenskins'
    static_configs:
      - targets: ['192.168.111.100:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.111.101:9100']