# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "shekeriev/centos-stream-9"
    jenkins.vm.hostname = "pipelines.do1.ex"
    jenkins.vm.network "private_network", ip: "192.168.111.100"
    jenkins.vm.network "forwarded_port", guest: 8080, host: 8080
    jenkins.vm.synced_folder ".", "/vagrant"
    jenkins.vm.provision "shell", path: "provision_scripts/add-hosts.sh"
    jenkins.vm.provision "shell", path: "provision_scripts/jenkins_install.sh"
    jenkins.vm.provision "shell", path: "provision_scripts/node-exporter.sh"
    jenkins.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "containers.do1.ex"
    docker.vm.network "private_network", ip: "192.168.111.101"
    docker.vm.network "forwarded_port", guest: 8080, host: 8081
    docker.vm.synced_folder ".", "/vagrant"
    docker.vm.provision "shell", path: "provision_scripts/add-hosts.sh"
    docker.vm.provision "shell", path: "provision_scripts/install_docker.sh"
    docker.vm.provision "shell", path: "gitea.sh"
    docker.vm.provision "shell", path: "provision_scripts/node-exporter.sh"    
    docker.vm.provider "virtualbox" do |v|
     v.gui = false
     v.memory = 4096
     v.cpus = 2
   end
 end
  
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.box = "shekeriev/centos-stream-9"
    monitoring.vm.hostname = "monitoring.do1.ex"
    monitoring.vm.network "private_network", ip: "192.168.111.102"
    monitoring.vm.network "forwarded_port", guest: 3000, host: 8082
    monitoring.vm.provision "shell", path: "provision_scripts/add-hosts.sh"
    monitoring.vm.provision "shell", path: "provision_scripts/install_docker_monitoring.sh"
    monitoring.vm.provision "shell", path: "provision_scripts/node-exporter.sh"
    monitoring.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
  end
end