# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="shekeriev/centos-stream-9"
    web.vm.boot_timeout = 600
    web.vm.hostname = "web"
    web.vm.synced_folder "./web/", "/vagrant"
    web.vm.network "private_network", ip: "192.168.99.100"
    web.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
    web.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    web.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end

  end

  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/debian-11"
    db.vm.boot_timeout = 600
    db.vm.hostname = "db.do2.lab"
    db.vm.network "private_network", ip: "192.168.99.101"
    db.vm.network "forwarded_port", guest: 3306, host: 3306, auto_correct: true
    db.vm.synced_folder "./db/", "/vagrant"
    db.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end
  end

  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-stream-9"
    ans.vm.boot_timeout = 600
    ans.vm.hostname = "ans.do2.lab"
    ans.vm.network "private_network", ip: "192.168.99.99"
    ans.vm.synced_folder "./", "/vagrant"
    ans.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end
    ans.vm.provision "shell", path: "install.sh"
  
  end
 
end
