# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "shekeriev/centos-stream-9"
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.99.100"
    jenkins.vm.synced_folder ".", "/vagrant"
    jenkins.vm.provision "shell", path: "add-hosts.sh"
    jenkins.vm.provision "shell", path: "provision_scripts/jenkins_install.sh"
    jenkins.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 2
    end
  end
  
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.synced_folder ".", "/vagrant"
    docker.vm.provision "shell", path: "add-hosts.sh"
    docker.vm.provision "shell", path: "provision_scripts/install_docker.sh"
    docker.vm.provision "shell", path: "provision_scripts/gitea.sh"
    docker.vm.provider "virtualbox" do |v|
     v.gui = false
     v.memory = 1024
     v.cpus = 2
   end
 end
  
#  config.vm.define "vm102.do1.ex" do |vm102.do1.ex|
#    vm102.do1.ex.vm.box = "shekeriev/centos-stream-9"
#    vm102.do1.ex.vm.hostname = "vm102.do1.ex"
#    vm102.do1.ex.vm.network "private_network", ip: "192.168.99.102"
#    vm102.do1.ex.vm.provision "shell", path: "add-hosts.sh"
#    vm102.do1.ex.vm.provision "shell", path: "------------"
#    vm102.do1.ex.vm.provider "virtualbox" do |v|
#      v.gui = false
#      v.memory = 1024
#      v.cpus = 2
#    end
#  end
end