# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="shekeriev/centos-stream-9"
    web.vm.boot_timeout = 600
    web.vm.hostname = "web"
    web.vm.synced_folder "./", "/vagrant"
    web.vm.network "private_network", ip: "192.168.99.100"
    web.vm.network "forwarded_port", guest: 80, host: 8000, auto_correct: true
    web.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    web.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end

  end
  config.vm.define "ans" do |ans|
    ans.vm.box = "shekeriev/centos-stream-9"
    ans.vm.boot_timeout = 600
    ans.vm.hostname = "ans.do2.lab"
    ans.vm.network "private_network", ip: "192.168.99.99"
    ans.vm.synced_folder "./", "/vagrant"
    ans.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "2048", "--cpus", "2"]
    end
    ans.vm.provision "shell", path: "install.sh"
  end  
end
