# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Salt Server - CentOS 9.x
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-9"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.100"
    server.vm.provision "shell", path: "add_hosts.sh"
	server.vm.provision "shell", path: "add_packages_centos.sh"

    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end
  end
  
  # Salt Client #1 - CentOS 9.x
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.provision "shell", path: "add_hosts.sh"
	docker.vm.provision "shell", path: "add_packages_centos.sh"

    docker.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 2
    end
  end

  # Salt Client #2 - Debian 11
  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/debian-11"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.99.102"
    web.vm.provision "shell", path: "add_hosts.sh"
	web.vm.provision "shell", path: "add_packages_debian.sh"

    web.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 2
    end
  end
  
  # Salt Client #3 - CentOS 9.x
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-stream-9"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.99.103"
    db.vm.provision "shell", path: "add_hosts.sh"
	db.vm.provision "shell", path: "add_packages_centos.sh"

    db.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 2
    end
  end
  
end
