# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modulesnginx = <<MODULESNGINX
    puppet module install puppetlabs-firewall --version 5.0.0
    puppet module install puppetlabs-docker --version 7.0.0
    sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESNGINX

  # NGINX - CentOS Stream 8
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-8"
    docker.vm.hostname = "nginx"
    docker.vm.network "private_network", ip: "192.168.99.100"
    docker.vm.network "forwarded_port", guest: 80, host: 80
    docker.vm.provision "shell", path: "add_hosts.sh"
    docker.vm.provision "shell", inline: $puppet, privileged: false
    docker.vm.provision "shell", inline: $modulesnginx, privileged: false

    docker.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "docker.pp"
      puppet.options = "--verbose --debug"
    end

    docker.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
  end
  
end