# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  $puppet = <<PUPPET
    sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
    sudo dnf install -y puppet
PUPPET

  $modulesdocker = <<MODULEDOCKER
    sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    sudo dnf install -y docker-ce docker-ce-cli containerd.io
    sudo systemctl enable --now docker
    sudo usermod -aG docker vagrant
    puppet module install puppetlabs-firewall
    puppet module install puppetlabs-docker
    sudo rsync -a ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/

MODULEDOCKER

  # WEB - CentOS Stream 8
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-8"
    docker.vm.hostname = "docker.do2.lab"
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.provision "shell", path: "add_hosts.sh"
    docker.vm.provision "shell", inline: $puppet, privileged: false
    docker.vm.provision "shell", inline: $modulesdocker, privileged: false
    docker.vm.provision "shell", path: "copy-manifest.sh"
    docker.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file = "docker.pp"
      puppet.options = "--verbose --debug"
    end
    docker.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 2
    end
  end
end
