global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'Rabbit-1'
    static_configs:
      - targets: ['192.168.99.101:9100']

  - job_name: 'Rabbit-2'
    static_configs:
      - targets: ['192.168.99.102:9100']

  - job_name: 'Rabbit-3'
    static_configs:
      - targets: ['192.168.99.103:9100']