global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - argets: ['localhost:9090']
      - argets: ['localhost:9323']

  - job_name: 'jenkins'
    static_configs:
      - targets: ['192.168.111.100:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ['192.168.111.101:9100']
      - targets: ['192.168.111.101:9323']