version: "3.8"

services:
    web:
        image: ivanovka87/hw3-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        networks:
            - app
        depends_on:
            - db

    db:
        image: ivanovka87/hw3-db
        networks:
            - app
        environment:
            MYSQL_ROOT_PASSWORD: "12345"

networks:
    app: