# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Salt Client #1 - CentOS 9.x
  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.99.101"
    docker.vm.provision "shell", path: "add_hosts.sh"
#   docker.vm.provision "shell", path: "chef-client.sh"
    docker.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 1024
      v.cpus = 2
    end
  end

  # Salt Server - CentOS 9.x
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-9"
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "192.168.99.100"
    server.vm.synced_folder "./", "/vagrant"
    server.vm.provision "shell", path: "add_hosts.sh"
	  server.vm.provision "shell", path: "Workstation.sh"    
#	  server.vm.provision "shell", path: "task-docker.sh"
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4000
      v.cpus = 2
    end
  end

  # Salt Client #1 - CentOS 9.x
#  config.vm.define "workstation" do |workstation|
#    workstation.vm.box = "shekeriev/centos-stream-9"
#    workstation.vm.hostname = "Workstation"
#    workstation.vm.network "private_network", ip: "192.168.99.102"
#    workstation.vm.provision "shell", path: "add_hosts.sh"
#    workstation.vm.provision "shell", path: "Workstation.sh"
#    workstation.vm.provider "virtualbox" do |v|
#      v.gui = false
#      v.memory = 1024
#      v.cpus = 2
#    end
#  end

end  
