# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
   v.gui = false
   v.memory = 2048
   v.cpus = 2
  end

  config.vm.define "docker" do |docker|
    docker.vm.box = "shekeriev/centos-stream-9"
    docker.vm.hostname = "Containers"
    docker.vm.network "private_network", ip: "192.168.99.100"

    docker.vm.provision "shell", inline: <<EOS
echo " Adding EPEL repository ..."
dnf install -y epel-release

echo " Installing Python3 ..."
dnf install -y python3 python3-pip

echo " Installing Python Docker module ..."
pip3 install docker
EOS

    docker.vm.provision "ansible_local" do |ansible|
       ansible.become = true
       ansible.install_mode = :default
       ansible.playbook = "ansible/docker.yml"
       ansible.galaxy_role_file = "ansible/docker-req.yml"
       ansible.galaxy_roles_path = "/etc/ansible/roles"
       ansible.galaxy_command = "sudo ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path} --force"
    end
    docker.vm.provision "shell", path: "forwarding.sh"
  end

  $puppetrpm = <<PUPPETRPM
  sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
  sudo dnf install -y puppet
PUPPETRPM

  $modulesweb = <<MODULESWEB
  puppet module install puppetlabs-vcsrepo
  puppet module install puppetlabs-firewall
  puppet module install puppet-selinux
  sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESWEB

   config.vm.define "web" do |web|
     web.vm.box = "shekeriev/centos-stream-8"
     web.vm.hostname = "web.server"
     web.vm.network "private_network", ip: "192.168.99.101"
     web.vm.provision "shell", inline: $puppetrpm, privileged: false
     web.vm.provision "shell", inline: $modulesweb, privileged: false
     
     web.vm.provision "puppet" do |puppet|
       puppet.manifests_path = "manifests"
       puppet.manifest_file = "web.pp"
       puppet.options = "--verbose --debug"
   end
  end

  $modulesdb = <<MODULESDB
  puppet module install puppetlabs-vcsrepo
  puppet module install puppetlabs/mysql
  puppet module install puppetlabs-firewall
  sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESDB

  config.vm.define "db" do |db|
   db.vm.box = "shekeriev/centos-stream-8"
   db.vm.hostname = "db.server"
   db.vm.network "private_network", ip: "192.168.99.102"
   db.vm.provision "shell", inline: $puppetrpm, privileged: false
   db.vm.provision "shell", inline: $modulesdb, privileged: false
   
   db.vm.provision "puppet" do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file = "db.pp"
     puppet.options = "--verbose --debug"
   end
  end
end
