# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
  
    $puppet = <<PUPPET
      sudo dnf install -y https://yum.puppet.com/puppet7-release-el-8.noarch.rpm
      sudo dnf install -y puppet
PUPPET
  
    $modulesweb = <<MODULESWEB
      puppet module install puppetlabs-firewall
      sudo cp -vR ~/.puppetlabs/etc/code/modules/ /etc/puppetlabs/code/
MODULESWEB
  
    $modulesdb = <<MODULESDB
      sudo apt-get update
      sudo apt-get install -y rsync
      sudo apt-get install -y puppet
      puppet module install puppetlabs-firewall
      puppet module install puppetlabs/mysql
      puppet module install puppetlabs/mysql
      sudo rsync -a ~/.puppet/etc/code/modules/ /etc/puppet/code/
MODULESDB
  
    # WEB - CentOS Stream 8
    config.vm.define "web" do |web|
      web.vm.box = "shekeriev/centos-stream-8"
      web.vm.hostname = "web.do2.lab"
      web.vm.network "private_network", ip: "192.168.99.101"
      web.vm.provision "shell", path: "add_hosts.sh"
      web.vm.provision "shell", inline: $puppet, privileged: false
      web.vm.provision "shell", inline: $modulesweb, privileged: false
      web.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "web.pp"
        puppet.options = "--verbose --debug"
      end
      web.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = 512
        v.cpus = 2
      end
    end
  
    # DB - debian
    config.vm.define "client2" do |client2|
      client2.vm.box = "ubuntu/bionic64"
      client2.vm.hostname = "db.do2.lab"
      client2.vm.network "private_network", ip: "192.168.99.102"
      client2.vm.provision "shell", path: "add_hosts.sh"
      client2.vm.provision "shell", inline: $modulesdb, privileged: false
  
      client2.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "manifests"
        puppet.manifest_file = "db.pp"
        puppet.options = "--verbose --debug"
      end
  
      client2.vm.provider "virtualbox" do |v|
        v.gui = false
        v.memory = 2048
        v.cpus = 2
      end
    end
    
  end