---
- hosts: webserver
  become: true
  tasks:
  - name: Install PHP packages
    package:
      name:
        - php
        - php-common
        - php-cli
      state: present
  - name: “Install EPEL repository”
    package:
       name: epel-release
       state: present
  - name: “Copy Files”
    copy:
       dest: /var/www/html/
       src: /vagrant/web/
       directory_mode: true
    notify: “web_restart”
  - name: “Starting Web Server”
    service:
       name: nginx
       state: started       
  handlers:
  - name: “web_restart”
    service:
       name: nginx
       state: restarted
  - name: Start Nginx service
    service:
        name: nginx
        state: started
        enabled: yes
- hosts: dbserver
  become: true
  tasks:
  - name: “Install MariaDB Server”
    apt:
      name: mariadb-server
      state: present
  - name: "Copy Database setup"
    copy:
       dest: /var/lib/mysql
       src: /vagrant/db/
  - name: “Starting Web Server”
    service:
       name: mariadb
       enabled: true
       state: started      