services:
    prometheus:
        image: prom/prometheus
        deploy:
            replicas: 1
        ports:
            - 9090:9090
        volumes:
            - "/tmp/prometheus.yml:/etc/prometheus/prometheus.yml"
    grafana:
        image: grafana/grafana
        depends_on:
            - prometheus
        ports:
            - 3000:3000
        volumes:
            - ./grafana/provisioning/:/etc/grafana/provisioning/
        restart: always