# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.box = "shekeriev/centos-stream-9"

  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.memory = 2048
    v.cpus = 2
  end

  # Apache Kafka Machines - CentOS Stream 9
  (1..1).each do |i|
    config.vm.define "kafka" do |kafka|
      kafka.vm.hostname = "kafka.do2.lab"
      kafka.vm.network "private_network", ip: "192.168.99.100"
      kafka.vm.provision "shell", path: "add_hosts.sh"
      kafka.vm.provision "shell", path: "kafka.sh"
    end
  end
  
  # Monitoring Machine - CentOS Stream 9
  config.vm.define "monitoring" do |monitoring|
    monitoring.vm.hostname = "monitoring.do2.lab"
    monitoring.vm.network "private_network", ip: "192.168.99.101"
    monitoring.vm.provision "shell", path: "add_hosts.sh"
    monitoring.vm.provision "shell", path: "monitoring.sh"
  end
end
