version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web.embedded
        ports:
            - 8080:80
        networks:
            - app
        depends_on:
            - db
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
