version: "3.8"
services:
    web:
        image: Ivanovka87/bgapp-web
        ports:
            - 80:80
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: Ivanovka87/bgapp-db
        networks:
            - app
        environment:
            MYSQL_ROOT_PASSWORD: "12345"
networks:
    app-network:
