# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  # Chef Server - CentOS Stream 9
  config.vm.define "server" do |server|
    server.vm.box = "shekeriev/centos-stream-9"
    server.vm.hostname = "chef-server"
    server.vm.network "private_network", ip: "192.168.99.101"
    server.vm.provision "shell", path: "add_hosts.sh"
    server.vm.provision "shell", path: "centos-pre.sh"
    server.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 4096
      v.cpus = 1
    end
  end
  
  # Chef Client #1 - CentOS Stream 9
  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/centos-stream-9"
    web.vm.hostname = "web"
    web.vm.network "private_network", ip: "192.168.99.102"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.provision "shell", path: "add_hosts.sh"
    web.vm.provision "shell", path: "centos-pre.sh"
    web.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 2048
      v.cpus = 1
    end
  end

  # Chef Client #2 - Debian 11
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/debian-11"
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.99.103"
    db.vm.provision "shell", path: "add_hosts.sh"
    db.vm.provision "shell", path: "db_installation.sh"
    db.vm.synced_folder "files/", "/vagrant"
    db.vm.provider "virtualbox" do |v|
      v.gui = false
      v.memory = 512
      v.cpus = 1
    end
  end
  
end